<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDCn8TFXGg17HAUcNpkwtxxyT9Io9B_NcM" defer></script>
<script src="{{asset('Backend/assets/plugins/jquery/jquery.min.js')}}"></script>
<script src="{{asset('Backend/assets/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<script src="{{asset('Backend/assets/plugins/toaster/toastr.min.js')}}"></script>
<script src="{{asset('Backend/assets/plugins/slimscrollbar/jquery.slimscroll.min.js')}}"></script>
<script src="{{asset('Backend/assets/plugins/charts/Chart.min.js')}}"></script>
<script src="{{asset('Backend/assets/plugins/ladda/spin.min.js')}}"></script>
<script src="{{asset('Backend/assets/plugins/ladda/ladda.min.js')}}"></script>
<script src="{{asset('Backend/assets/plugins/jquery-mask-input/jquery.mask.min.js')}}"></script>
<script src="{{asset('Backend/assets/plugins/select2/js/select2.min.js')}}"></script>
<script src="{{asset('Backend/assets/plugins/jvectormap/jquery-jvectormap-2.0.3.min.js')}}"></script>
<script src="{{asset('Backend/assets/plugins/jvectormap/jquery-jvectormap-world-mill.js')}}"></script>
<script src="{{asset('Backend/assets/plugins/daterangepicker/moment.min.js')}}"></script>
<script src="{{asset('Backend/assets/plugins/daterangepicker/daterangepicker.js')}}"></script>
<script src="{{asset('Backend/assets/plugins/jekyll-search.min.js')}}"></script>
<script src="{{asset('Backend/assets/js/sleek.js')}}"></script>
<script src="{{asset('Backend/assets/js/chart.js')}}"></script>
<script src="{{asset('Backend/assets/js/date-range.js')}}"></script>
<script src="{{asset('Backend/assets/js/map.js')}}"></script>
<script src="{{asset('Backend/assets/js/custom.js')}}"></script>
<script src="{{asset('Backend/assets/js/toastr.min.js')}}"></script>
<!--Frontend JS-->

<script src="{{asset('Frontend/js/jquery-3.2.1.min.js')}}"></script>
<script src="{{asset('Frontend/styles/popper.js')}}"></script>
<script src="{{asset('Frontend/styles/bootstrap.min.js')}}"></script>
<script src="{{asset('Frontend/plugins/greensock/TweenMax.min.js')}}"></script>
<script src="{{asset('Frontend/plugins/greensock/TimelineMax.min.js')}}"></script>
<script src="{{asset('Frontend/plugins/scrollmagic/ScrollMagic.min.js')}}"></script>
<script src="{{asset('Frontend/plugins/greensock/animation.gsap.min.js')}}"></script>
<script src="{{asset('Frontend/plugins/greensock/ScrollToPlugin.min.js')}}"></script>
<script src="{{asset('Frontend/plugins/OwlCarousel2-2.2.1/owl.carousel.js')}}"></script>
<script src="{{asset('Frontend/plugins/Isotope/isotope.pkgd.min.js')}}"></script>
<script src="{{asset('Frontend/plugins/easing/easing.js')}}"></script>
<script src="{{asset('Frontend/plugins/parallax-js-master/parallax.min.js')}}"></script>
<script src="{{asset('Frontend/js/product.js')}}"></script>
